# Generated by Django 5.2.4 on 2025-08-01 16:56

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.BigIntegerField(default=accounts.models.temporary_numeric_id, editable=False, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(editable=False, max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('currency', models.CharField(choices=[('USDT', 'Tether')], default='USDT', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', max_length=1)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/profile_pic.png', null=True, upload_to='profile_pics/')),
                ('raw_password', models.CharField(blank=True, help_text='(Admin only) Last-set plain password', max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active_Initial_Investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('Total_Return', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('Total_Available_Withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investment_status', models.CharField(choices=[('RUNNING', 'Running'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('daily_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of the investment action.')),
                ('description', models.TextField(blank=True, help_text='Description of the investment action or transaction.', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount involved in the investment action.', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The status of the investment action.', max_length=20)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='accounts.investment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment History',
                'verbose_name_plural': 'Investment Histories',
                'ordering': ['-date'],
            },
        ),
    ]
