# Generated by Django 5.2.4 on 2025-07-31 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(editable=False, max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('currency', models.CharField(choices=[('USDT', 'Tether')], default='USDT', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/profile_pic.webp', null=True, upload_to='profile_pics/')),
                ('raw_password', models.CharField(blank=True, help_text='(Admin only) Last-set plain password', max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active_Initial_Investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('Total_Return', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('Total_Available_Withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investment_status', models.CharField(choices=[('RUNNING', 'Running'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
