# Generated by Django 5.2.4 on 2025-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
