# Generated by Django 5.2.4 on 2025-08-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('HKD', 'Hong Kong Dollar'), ('SGD', 'Singapore Dollar'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('ZAR', 'South African Rand'), ('RUB', 'Russian Ruble'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('EGP', 'Egyptian Pound'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('PKR', 'Pakistani Rupee'), ('BDT', 'Bangladeshi Taka'), ('THB', 'Thai Baht'), ('IDR', 'Indonesian Rupiah'), ('MYR', 'Malaysian Ringgit'), ('PHP', 'Philippine Peso')], default='USD', max_length=10),
        ),
    ]
