# Generated by Django 5.2.4 on 2025-08-14 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProfitCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credited_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_credits', to='accounts.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_profit_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-credited_date'],
                'unique_together': {('user', 'investment', 'credited_date')},
            },
        ),
    ]
