# Generated by Django 5.2.4 on 2025-08-01 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of the investment action.')),
                ('description', models.TextField(blank=True, help_text='Description of the investment action or transaction.', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount involved in the investment action.', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The status of the investment action.', max_length=20)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='accounts.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment History',
                'verbose_name_plural': 'Investment Histories',
                'ordering': ['-date'],
            },
        ),
    ]
