# Generated by Django 5.2.4 on 2025-08-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_investmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
