# Generated by Django 5.2.4 on 2025-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_investmenthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenthistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The status of the investment action.', max_length=20),
        ),
    ]
