"""
Django settings for investment project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-po9mjbwl!3d6$izl3@g4ece$p6nk4#2zak8dcfw3m_thcrb2al'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://wallet.gm-sach.com"]
ALLOWED_HOSTS = ["wallet.gm-sach.com"]



# settings.py
LOGIN_URL = '/client_login/'

# Application definition
AUTH_USER_MODEL = 'accounts.Account'

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'investment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'core/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'investment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'core/static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = env('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False


from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_HEADER": "Gm Admin",
    "SITE_TITLE": "Gm Admin Panel",
    "SITE_SUBHEADER": "Gm Admin Panel",
    "SITE_URL": "/",
    "SHOW_SIDEBAR": True,
    "SITE_ICON": {
        "light": lambda request: static("assets/img/logos/logo.png"),
        "dark": lambda request: static("assets/img/logos/logo.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/img/logos/logo.png"),
        "dark": lambda request: static("assets/img/logos/logo.png"),
    },
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": True,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:accounts_account_changelist"),
                "description": _("Manage registered users."),
            },
            {
                "title": _("Balances"),
                "icon": "account_balance_wallet",
                "link": reverse_lazy("admin:accounts_balance_changelist"),
                "description": _("User balance details."),
            },
            {
                "title": _("Investments"),
                "icon": "trending_up",
                "link": reverse_lazy("admin:accounts_investment_changelist"),
                "description": _("Manage user investments."),
            },
            {
                "title": _("Investment History"),
                "icon": "history",
                "link": reverse_lazy("admin:accounts_investmenthistory_changelist"),
                "description": _("Track investment history."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("User & Investment Management"),
                "icon": "account_circle",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Accounts"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_account_changelist"),
                    },
                    {
                        "title": _("Balances"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:accounts_balance_changelist"),
                    },
                    {
                        "title": _("Investments"),
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:accounts_investment_changelist"),
                    },
                    {
                        "title": _("Investment History"),
                        "icon": "history",
                        "link": reverse_lazy("admin:accounts_investmenthistory_changelist"),
                    },
                ],
            },
        ],
    },
}
